---
- name: Install Docker 
  block:
    - name: Install dependecies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu groovy stable
        state: present

    - name: Install Docker engine
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python3-pip

    - name: Install python Docker sdk
      pip:
        name: docker 
