---
- name: Set task variables
  set_fact:
    dotfiles_path: /home/chl/Documents/code/dotfiles

- block:
  - name: Create code dir structure 
    file:
      path: /home/chl/Documents/code 
      state: directory
      owner: chl
      mode: 0755

  - name: Clone dotfiles repo
    git: 
      repo: git@github.com:strong-code/dotfiles.git 
      dest: "{{ dotfiles_path }}" 
      version: master
      accept_hostkey: yes

    # Since cloning with ssh agent-forwarding gives root ownership
  - name: Change local dotfile repo ownership
    file:
      path: "{{ dotfiles_path }}"
      owner: chl
      group: chl
      mode: u=rwX,g=rX,o=rX
      recurse: yes
      state: directory

  become: yes
  become_user: root

- block:
  - name: Clear out DO gargabe
    file:
      path: "~/.{{ item }}"
      state: absent
    loop:
      - bash_logout
      - bashrc
      - profile  

  - name: Symlink .bash_profile
    file:
      src: "{{ dotfiles_path }}/.bash_profile"
      dest: ~/.bash_profile
      owner: chl
      state: link

  - name: Create ~/.ssh directory
    file:
      path: ~/.ssh
      state: directory
      owner: chl
      mode: 0755

  - name: Symlink authorized_keys
    file:
      src: "{{ dotfiles_path }}/server/authorized_keys"
      dest: ~/.ssh/authorized_keys
      owner: chl
      mode: 0644
      state: link

  - name: Symlink sshd_config
    file:
      src: "{{ dotfiles_path }}/server/sshd_config"
      dest: /etc/ssh/sshd_config
      owner: root
      mode: 0644
      state: link
      force: yes
    become: yes
    become_user: root

  - name: Add crontab
    command: "crontab {{ dotfiles_path }}/server/.crontab" 

  - name: Symlink irssi directory
    file:
      src: "{{ dotfiles_path }}/irssi"
      dest: ~/.irssi
      owner: chl
      state: link

  - name: Symlink tmux conf
    file:
      src: "{{ dotfiles_path }}/tmux/.tmux.conf"
      dest: ~/.tmux.conf
      owner: chl
      state: link

  - name: Symlink tmux directory
    file:
      src: "{{ dotfiles_path }}/tmux/.tmux"
      dest: ~/.tmux
      owner: chl
      state: link

  - name: Symlink vim directory
    file:
      src: "{{ dotfiles_path }}/vim/.vim"
      dest: ~/.vim
      owner: chl
      state: link

  - name: Symlink .vimrc
    file:
      src: "{{ dotfiles_path }}/vim/.vimrc"
      dest: ~/.vimrc
      owner: chl
      state: link

  - name: Symlink global git files
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest}}"
      owner: chl
      state: link
    loop:
      - { src: "{{ dotfiles_path }}/git/.git-prompt.sh", dest: '~/.git-prompt.sh' }
      - { src: "{{ dotfiles_path }}/git/.gitconfig", dest: '~/.gitconfig' }
      - { src: "{{ dotfiles_path }}/git/.gitignore", dest: '~/.gitignore' }

  become: yes
  become_user: chl

- name:
  find:
    paths: "{{ dotfiles_path }}/server/init"
  register: service_dir

- name: Symlink systemd service files
  file:
    src: "{{ item.path }}" 
    dest: "/etc/systemd/system/{{ item.path | basename }}"
    owner: root
    state: link
  with_items: "{{ service_dir.files }}"

- name: Force daemon-reload
  systemd:
    daemon_reload: yes
