---
- block:
  - name: Set task variables
    set_fact:
      dotfiles_path: /home/chl/Documents/code/dotfiles

  - name: Clear out DO gargabe
    file:
      path: "~/.{{ item }}"
      state: absent
    loop:
      - bash_logout
      - bashrc
      - profile  

  - name: Create code dir structure 
    file:
      path: ~/Documents/code 
      state: directory
      owner: chl
      mode: 0755

  - name: Clone dotfiles repo
    git: 
      repo: https://github.com/strong-code/dotfiles.git 
      dest: "{{ dotfiles_path }}" 
      version: master
      accept_hostkey: yes

  - name: Symlink .bash_profile
    file:
      src: "{{ dotfiles_path }}/.bash_profile"
      dest: ~/.bash_profile
      owner: chl
      state: link

  - name: Create ~/.ssh directory
    file:
      path: ~/.ssh
      state: directory
      owner: chl
      mode: 0755

  - name: Symlink authorized_keys
    file:
      src: "{{ dotfiles_path }}/server/authorized_keys"
      dest: ~/.ssh/authorized_keys
      owner: chl
      mode: 0644
      state: link

  - name: Add crontab
    command: "crontab {{ dotfiles_path }}/server/.crontab" 

  - name: Symlink irssi directory
    file:
      src: "{{ dotfiles_path }}/irssi"
      dest: ~/.irssi
      owner: chl
      state: link

  - name: Symlink tmux conf
    file:
      src: "{{ dotfiles_path }}/tmux/.tmux.conf"
      dest: ~/.tmux.conf
      owner: chl
      state: link

  - name: Symlink tmux directory
    file:
      src: "{{ dotfiles_path }}/tmux/.tmux"
      dest: ~/.tmux
      owner: chl
      state: link

  - name: Symlink vim directory
    file:
      src: "{{ dotfiles_path }}/vim/.vim"
      dest: ~/.vim
      owner: chl
      state: link

  - name: Symlink .vimrc
    file:
      src: "{{ dotfiles_path }}/vim/.vimrc"
      dest: ~/.vimrc
      owner: chl
      state: link

  - name: Symlink global git files
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest}}"
      owner: chl
      state: link
    loop:
      - { src: "{{ dotfiles_path }}/git/.git-prompt.sh", dest: '~/.git-prompt.sh' }
      - { src: "{{ dotfiles_path }}/git/.gitconfig", dest: '~/.gitconfig' }
      - { src: "{{ dotfiles_path }}/git/.gitignore", dest: '~/.gitignore' }

  become: yes
  become_user: chl
