---
# Note: irssi directory (config, theme, scripts) is symlinked by tasks/dotfiles.yml
- name: Install irssi
  apt:
    name: irssi
    state: present

- name: Create irssi log directory
  file:
    path: /var/log/irssi
    state: directory
    owner: chl

