---
- name: Install nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Symlink sites-enabled
  file: 
    src: /home/chl/Documents/code/dotfiles/server/sites-enabled
    dest: /etc/nginx/sites-enabled
    state: link
    mode: 0755
    force: yes
