---
#
# Note that any package that is a dependency for a task run
# should go in the corresponding task file. This makes it much
# easier to keep track of packages when changing/removing/adding tasks
#
- name: Remove unwanted packages
  apt:
    name: gnome-keyring
    state: absent

- name: Install user packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - curl
    - git
    - jq
    - postgresql-12

- name: Install nodejs plugin requirements
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - dirmngr
    - gpg

- name: Install asdf globally
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: /opt/asdf

- name: Set group permissions on /opt/asdf
  file:
    path: /opt/asdf
    owner: chl
    group: asdf
    state: directory
    recurse: yes
    mode: u=rwX,g=rX,o=r

