---
#
# Note that any package that is a dependency for a task run
# should go in the corresponding task file. This makes it much
# easier to keep track of packages when changing/removing/adding tasks
#
- name: Install user packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - curl
    - git

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
