---
#
# Note that any package that is a dependency for a task run
# should go in the corresponding task file. This makes it much
# easier to keep track of packages when changing/removing/adding tasks
#
- name: Install user packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - curl
    - git
    - jq
    - postgresql-12

- name: Install nodejs plugin requirements
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - dirmngr
    - gpg

- block:
  - name: Install asdf
    git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: ~/.asdf
    become: yes
    become_user: chl

  - name: Install nodejs plugin
    command: "${HOME}/.asdf/bin/asdf plugin add nodejs"
    register: nodejs_add
    failed_when: nodejs_add == 2

  become: yes
  become_user: chl
