---
- name: Create pihole data dir
  file: 
    path: /etc/pihole
    state: directory
    mode: 0755 

- name: Create dnsmasq.d data dir
  file:
    path: /etc/dnsmasq.d
    state: directory 
    mode: 0755

- name: Pull down and run pihole docker container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    pull: true
    state: started
    detach: yes
    restart_policy: unless-stopped
    hostname: pi.hole
    published_ports:
      - "{{ ansible_default_ipv4.address }}:53:53/tcp"
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
      - "{{ ansible_default_ipv4.address }}:80:80"
      - "{{ ansible_default_ipv4.address }}:443:443"
    dns_servers:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - /etc/pihole/:/etc/pihole/
      - /etc/dnsmasq.d/:/etc/dnsmasq.d/
    env:
      VIRTUAL_HOST: pi.hole
      PROXY_LOCATION: pi.hole
      TZ: America/Los Angeles
      ServerIP: "{{ ansible_default_ipv4.address }}"

