---
- name: Create prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755

- name: Copy prometheus.yml
  template:
    src: prometheus.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root

- name: Pull latest prometheus image
  docker_container:
    name: prometheus
    image: prom/prometheus:master
    pull: true
    state: started
    restart: yes
    detach: yes
    restart_policy: unless-stopped
    published_ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /etc/prometheus/:/etc/prometheus/
    networks:
      - name: prom-grafana
    purge_networks: yes

- name: Download and unarchive node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz 
    dest: /etc/prometheus
    remote_src: yes

- name: start local node_exporter service
  systemd:
    state: started
    name: node_exporter.service
    daemon_reload: yes
