---
- name: Create admin group
  group:
    name: admin
    state: present

- name: Create deploy group
  group:
    name: deploy
    state: present

- name: Add chl user and admin/deploy group
  user:
    name: chl
    shell: /bin/bash
    groups: admin,deploy
