---
- name: Create admin group
  group:
    name: admin
    state: present

- name: Create deploy group
  group:
    name: deploy
    state: present

- name: Add chl user and admin/deploy group
  user:
    name: chl
    shell: /bin/bash
    groups: admin,deploy

- name: Allow admin group to have password-less sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
