---
- name: Create user groups
  group:
    name: "{{ item }}"
    state: present
  loop:
    - admin
    - deploy
    - botto

- name: Add chl user and admin/deploy group
  user:
    name: chl
    shell: /bin/bash
    groups: admin,deploy

- name: Add botto user
  user:
    name: botto
    shell: /bin/bash
    group: botto

- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash
    group: deploy

- name: Allow admin group to have password-less sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
